Repository ansible-collections/community.hashi_vault, pull requests merged in 2020-12, with the labels that each got.

#27 Add parameter to support X-Vault-AWS-IAM-Server-ID
  changelogs/fragments/27-add-hashi_vault-header_value-param.yml
  plugins/lookup/hashi_vault.py
Labels: enhancement

#26 CI/Tests - Caching, multiple vault versions, etc.
  .github/workflows/ansible-test.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/files/bin/.gitignore
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/handlers/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_download.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/vars/.gitignore
  tests/integration/targets/lookup_hashi_vault/playbooks/download_vault.yml
  tests/integration/targets/lookup_hashi_vault/playbooks/test_lookup_hashi_vault.yml
Labels: enhancement

#25 hashi_vault - parameter env var changes for token and namespace
  changelogs/fragments/25-non-breaking-env-parameter-changes.yml
  plugins/lookup/hashi_vault.py
Labels: enhancement

#22 hashi_vault - add support for using mount_point with aws_iam_login auth
  changelogs/fragments/22-hashi_vault-aws_iam_login-mount_point.yml
  plugins/lookup/hashi_vault.py
Labels: bug

#33 hashi_vault - add AppRole deprecation and fix invalid deprecation logic
  changelogs/fragments/33-approle-deprecation.yml
  plugins/lookup/hashi_vault.py
Labels: bug, enhancement

#31 hashi_vault - refactor tests with mount_point capabilities. fix jwt mount_point options
  changelogs/fragments/31-jwt-mount_point.yml
  plugins/lookup/hashi_vault.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_test.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/jwt_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/jwt_test.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server_auth_setup.yml
Labels: bug, tests

#24 hashi_vault - enable use of tokens without lookup-self
  changelogs/fragments/23-hashi_vault-token_validation.yml
  plugins/lookup/hashi_vault.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
Labels: bug, enhancement

#36 hashi_vault - environment variable deprecations (and one addition)
  changelogs/fragments/35-env-var-deprecations.yml
  plugins/lookup/hashi_vault.py
Labels: enhancement

#39 First pass at GH release automation
  .github/workflows/github-release.yml
Labels: ci

#40 Release/automation
  .github/workflows/github-release.yml
Labels: ci

#41 hashi_vault - lower VAULT_ADDR precedence
  changelogs/fragments/41-lower-url-env-precedence.yml
  plugins/lookup/hashi_vault.py
Labels: enhancement
