Repository ansible-collections/community.hashi_vault, pull requests merged in 2021-02, with the labels that each got.

#50 hashi_vault - add 'proxy' option
  changelogs/fragments/50-add-proxies-option.yml
  plugins/lookup/hashi_vault.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/handlers/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tinyproxy_server.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
Labels: enhancement

#56 Fix codecov paths
  codecov.yml
Labels: ci

#55 first steps at centralizing code and adding unit tests
  .github/workflows/ansible-test.yml
  plugins/lookup/__init__.py
  plugins/lookup/hashi_vault.py
  plugins/module_utils/hashi_vault_common.py
  plugins/plugin_utils/hashi_vault_plugin.py
  tests/unit/compat/__init__.py
  tests/unit/compat/builtins.py
  tests/unit/compat/mock.py
  tests/unit/compat/unittest.py
  tests/unit/plugins/base/test_hashi_vault_lookup_base.py
  tests/unit/plugins/base/test_hashi_vault_plugin.py
  tests/unit/plugins/lookup/test_hashi_vault.py
  tests/unit/plugins/module_utils/test_hashi_vault_common.py
  tests/unit/requirements.txt
Labels: ci, enhancement, tests

#61 hashi_vault - Fix regression where VAULT_ADDR is ignored
  changelogs/fragments/41-fix-vault-addr.yml
  plugins/lookup/hashi_vault.py
  tests/unit/plugins/lookup/test_hashi_vault.py
Labels: bug
