Repository ansible-collections/community.hashi_vault, pull requests merged in 2021-11, with the labels that each got.

#172 add action group
  changelogs/fragments/172-action_group.yml
  meta/runtime.yml
Labels: enhancement

#175 fix macos docker in CI
  .github/actions/macos-docker/action.yml
Labels: ci

#171 auth: add env and ini var for mount_point option
  changelogs/fragments/pr-171-envvar-for-mount-point.yaml
  plugins/doc_fragments/auth.py
Labels: enhancement

#176 connection options - make `url` required and remove the default value
  changelogs/fragments/176-url-is-required.yml
  plugins/doc_fragments/connection.py
  plugins/module_utils/_connection_options.py
  plugins/module_utils/_hashi_vault_common.py
  tests/unit/plugins/lookup/test_hashi_vault.py
  tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py
Labels: enhancement

#183 docs build - try head_ref to fix concurrency issues
  .github/workflows/docs-full.yml
  .github/workflows/docs.yml
Labels: documentation, ci

#186 Reduce codecov flags
  .github/actions/ansible-codecov/action.yml
  .github/workflows/ansible-test.yml
Labels: ci

#188 add missing codecov flag file association for auth_cert
  codecov.yml
Labels: ci

#191 Remove legacy test setup
  .github/workflows/ansible-test.yml
  changelogs/fragments/191-remove-legacy-integration.yml
  docs/docsite/rst/contributor_guide.rst
  docs/docsite/rst/localenv_developer_guide.rst
  tests/integration/.ansible-lint
  tests/integration/integration_config.yml.sample
  tests/integration/targets/auth_approle/aliases
  tests/integration/targets/auth_approle/meta/main.yml
  tests/integration/targets/auth_cert/aliases
  tests/integration/targets/auth_cert/meta/main.yml
  tests/integration/targets/auth_jwt/aliases
  tests/integration/targets/auth_jwt/meta/main.yml
  tests/integration/targets/auth_none/aliases
  tests/integration/targets/auth_none/meta/main.yml
  tests/integration/targets/auth_token/aliases
  tests/integration/targets/auth_token/meta/main.yml
  tests/integration/targets/connection_options/meta/main.yml
  tests/integration/targets/lookup_hashi_vault/aliases
  tests/integration/targets/lookup_hashi_vault/meta/main.yml
  tests/integration/targets/lookup_vault_read/aliases
  tests/integration/targets/lookup_vault_read/meta/main.yml
  tests/integration/targets/module_vault_read/aliases
  tests/integration/targets/module_vault_read/meta/main.yml
  tests/integration/targets/setup_tinyproxy_server/README.md
  tests/integration/targets/setup_tinyproxy_server/aliases
  tests/integration/targets/setup_tinyproxy_server/defaults/main.yml
  tests/integration/targets/setup_tinyproxy_server/handlers/main.yml
  tests/integration/targets/setup_tinyproxy_server/tasks/main.yml
  tests/integration/targets/setup_vault_legacy/README.md
  tests/integration/targets/setup_vault_legacy/aliases
  tests/integration/targets/setup_vault_legacy/defaults/main.yml
  tests/integration/targets/setup_vault_legacy/tasks/main.yml
  tests/integration/targets/setup_vault_server/README.md
  tests/integration/targets/setup_vault_server/aliases
  tests/integration/targets/setup_vault_server/defaults/main.yml
  tests/integration/targets/setup_vault_server/handlers/main.yml
  tests/integration/targets/setup_vault_server/tasks/main.yml
  tests/integration/targets/setup_vault_server/tasks/vault_server.yml
  tests/integration/targets/setup_vault_server/templates/vault_config.hcl.j2
  tests/integration/targets/setup_vault_server_download/README.md
  tests/integration/targets/setup_vault_server_download/aliases
  tests/integration/targets/setup_vault_server_download/defaults/main.yml
  tests/integration/targets/setup_vault_server_download/files/.gitignore
  tests/integration/targets/setup_vault_server_download/tasks/latest.yml
  tests/integration/targets/setup_vault_server_download/tasks/main.yml
Labels: tests, ci

#192 add userpass auth tests
  .github/workflows/ansible-test.yml
  plugins/module_utils/_auth_method_jwt.py
  tests/integration/targets/auth_userpass/aliases
  tests/integration/targets/auth_userpass/defaults/main.yml
  tests/integration/targets/auth_userpass/meta/main.yml
  tests/integration/targets/auth_userpass/tasks/main.yml
  tests/integration/targets/auth_userpass/tasks/userpass_setup.yml
  tests/integration/targets/auth_userpass/tasks/userpass_test_controller.yml
  tests/integration/targets/auth_userpass/tasks/userpass_test_target.yml
  tests/unit/plugins/module_utils/authentication/fixtures/userpass_login_response.json
  tests/unit/plugins/module_utils/authentication/test_auth_userpass.py
Labels: tests

#193 aws_iam auth - rename auth method, add tests
  changelogs/fragments/193-rename-aws-iam-auth.yml
  codecov.yml
  docs/docsite/rst/localenv_developer_guide.rst
  plugins/doc_fragments/auth.py
  plugins/lookup/hashi_vault.py
  plugins/module_utils/_auth_method_aws_iam.py
  plugins/module_utils/_authenticator.py
  tests/integration/targets/auth_aws_iam/aliases
  tests/integration/targets/auth_aws_iam/defaults/main.yml
  tests/integration/targets/auth_aws_iam/meta/main.yml
  tests/integration/targets/auth_aws_iam/tasks/aws_iam_test_controller.yml
  tests/integration/targets/auth_aws_iam/tasks/aws_iam_test_target.yml
  tests/integration/targets/auth_aws_iam/tasks/main.yml
  tests/integration/targets/setup_localenv_docker/defaults/main.yml
  tests/integration/targets/setup_localenv_docker/tasks/main.yml
  tests/integration/targets/setup_localenv_docker/templates/docker-compose.yml.j2
  tests/integration/targets/setup_localenv_docker/templates/mmock/aws_iam_login_alt_mount.yml.j2
  tests/integration/targets/setup_localenv_docker/templates/mmock/aws_iam_login_bad_request.yml.j2
  tests/integration/targets/setup_localenv_docker/templates/mmock/aws_iam_login_default_mount.yml.j2
  tests/integration/targets/setup_localenv_docker/templates/mmock/proxy.yml.j2
  tests/integration/targets/setup_localenv_docker/vars/main.yml
  tests/unit/plugins/module_utils/authentication/fixtures/aws_iam_login_response.json
  tests/unit/plugins/module_utils/authentication/test_auth_aws_iam.py
  tests/unit/plugins/module_utils/authentication/test_auth_aws_iam_login.py
  tests/unit/plugins/module_utils/authentication/test_hashi_vault_authenticator.py
Labels: enhancement, tests
