Repository ansible-collections/community.hashi_vault, pull requests merged in 2021-06, with the labels that each got.

#86 Add ability to use ansible vars to specify options
  changelogs/fragments/86-add-vars-options.yml
  plugins/doc_fragments/connection.py
  plugins/lookup/hashi_vault.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
Labels: enhancement, tests

#88 tests - replace use of Vault CLI to configure the Vault server
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_enable_auth.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_enable_engine.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_kv_put.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_policy_put.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_read.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_token_create.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/library/vault_ci_write.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_test.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/jwt_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_test.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml
Labels: tests

#90 tests - centralize vault addresses, better test control, split config vs. server start
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_secret_id_less_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/approle_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/jwt_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/token_setup.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/vault_server_configure.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/templates/vault_config.hcl.j2
Labels: tests

#92 tests - allow for external proxy
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
Labels: tests

#80 hashi_vault - add support for `none` auth type
  changelogs/fragments/80-add-none-auth-type.yml
  plugins/lookup/hashi_vault.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/main.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/none_test.yml
Labels: enhancement

#95 add more vars options (token path, token file, validate certs)
  changelogs/fragments/95-more-vars-options.yml
  plugins/doc_fragments/connection.py
  plugins/lookup/hashi_vault.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
Labels: enhancement

#97 hashi_vault - add alternate methods (env, ini, vars) for `ca_cert` option
  changelogs/fragments/97-ca_cert-env-and-vars.yml
  plugins/doc_fragments/connection.py
  plugins/module_utils/_hashi_vault_common.py
Labels: enhancement

#96 hashi_vault - add env and vars for userpass options
  changelogs/fragments/96-userpass-vars-env.yml
  plugins/lookup/hashi_vault.py
Labels: enhancement

#100 hashi_vault lookup - add `timeout` connection option
  plugins/doc_fragments/100-add-timeout-option.yml
  plugins/doc_fragments/connection.py
  plugins/module_utils/_hashi_vault_common.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
  tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py
Labels: enhancement

#71 hashi_vault - add retries option to allow for retrying failed requests
  .github/workflows/ansible-test.yml
  .github/workflows/antisibull-lint.yml
  changelogs/fragments/71-add-retries.yml
  docs/docsite/extra-docs.yml
  docs/docsite/rst/user_guide.rst
  plugins/doc_fragments/connection.py
  plugins/lookup/hashi_vault.py
  plugins/module_utils/_hashi_vault_common.py
  plugins/plugin_utils/_hashi_vault_plugin.py
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/tasks/tests.yml
  tests/unit/plugins/module_utils/test_hashi_vault_connection_options.py
  tests/unit/requirements.txt
  tests/utils/constraints.txt
Labels: enhancement

#101 tests - update Vault to 1.7.3
  .github/workflows/ansible-test.yml
  tests/integration/targets/lookup_hashi_vault/lookup_hashi_vault/defaults/main.yml
Labels: ci, tests

#103 Release 1.3.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  docs/docsite/extra-docs.yml
  galaxy.yml
Labels: documentation
