Repository ansible-collections/community.hashi_vault, pull requests merged in 2022-08, with the labels that each got.

#291 Fix "Unsafe" token values that originate from lookups
  changelogs/fragments/289-handle-unsafe-strings.yml
  plugins/module_utils/_auth_method_token.py
  plugins/module_utils/_hashi_vault_common.py
  tests/unit/plugins/module_utils/authentication/test_hashi_vault_auth_method_base.py
  tests/unit/plugins/module_utils/test_hashi_vault_helper.py
  tests/unit/plugins/plugin_utils/authentication/conftest.py
  tests/unit/plugins/plugin_utils/authentication/test_auth_token.py
  tests/unit/plugins/plugin_utils/test_hashi_vault_common_stringify.py
  tests/unit/plugins/plugin_utils/test_hashi_vault_helper.py
Labels: bug

#292 Add HTTP `412` to default retry list
  changelogs/fragments/290-retry-http-412.yml
  docs/docsite/rst/user_guide.rst
  plugins/module_utils/_connection_options.py
Labels: enhancement

#297 Sanity/use before assignment
  changelogs/fragments/296-use-before-assignment.yml
  plugins/modules/vault_kv1_get.py
  plugins/modules/vault_kv2_get.py
  plugins/modules/vault_login.py
  plugins/modules/vault_pki_generate_certificate.py
  plugins/modules/vault_read.py
  plugins/modules/vault_write.py
Labels: bug, tests, ci

#293 Add support for azure auth method
  changelogs/fragments/293-support-azure-auth-method.yml
  codecov.yml
  docs/docsite/rst/user_guide.rst
  meta/ee-requirements.txt
  plugins/doc_fragments/auth.py
  plugins/module_utils/_auth_method_azure.py
  plugins/module_utils/_authenticator.py
  tests/integration/requirements.txt
  tests/integration/targets/auth_azure/aliases
  tests/integration/targets/auth_azure/defaults/main.yml
  tests/integration/targets/auth_azure/meta/main.yml
  tests/integration/targets/auth_azure/tasks/azure_test_controller.yml
  tests/integration/targets/auth_azure/tasks/azure_test_target.yml
  tests/integration/targets/auth_azure/tasks/main.yml
  tests/integration/targets/setup_localenv_docker/templates/mmock/azure_login_alt_mount.yml.j2
  tests/integration/targets/setup_localenv_docker/templates/mmock/azure_login_bad_request.yml.j2
  tests/integration/targets/setup_localenv_docker/templates/mmock/azure_login_default_mount.yml.j2
  tests/unit/fixtures/azure_login_response.json
  tests/unit/plugins/module_utils/authentication/test_auth_azure.py
  tests/unit/requirements.txt
Labels: enhancement

#299 add the changelog to the collection docsite
  README.md
  docs/docsite/extra-docs.yml
  docs/docsite/rst/CHANGELOG.rst
Labels: documentation
