Repository ansible-collections/community.hashi_vault, pull requests merged in 2022-02, with the labels that each got.

#215 Docs/build updates
  .github/workflows/docs-push.yml
  .github/workflows/docs.yml
  docs/preview/conf.py
Labels: documentation

#216 Add module `vault_pki_generate_certificate`
  .github/workflows/ansible-test.yml
  codecov.yml
  plugins/modules/vault_pki_generate_certificate.py
  tests/integration/targets/module_vault_pki_generate_certificate/aliases
  tests/integration/targets/module_vault_pki_generate_certificate/meta/main.yml
  tests/integration/targets/module_vault_pki_generate_certificate/tasks/main.yml
  tests/integration/targets/module_vault_pki_generate_certificate/tasks/module_vault_pki_generate_certificate_setup.yml
  tests/integration/targets/module_vault_pki_generate_certificate/tasks/module_vault_pki_generate_certificate_test.yml
  tests/integration/targets/setup_vault_configure_engine_pki/README.md
  tests/integration/targets/setup_vault_configure_engine_pki/aliases
  tests/integration/targets/setup_vault_configure_engine_pki/meta/main.yml
  tests/integration/targets/setup_vault_configure_engine_pki/tasks/configure.yml
  tests/integration/targets/setup_vault_configure_engine_pki/tasks/main.yml
  tests/integration/targets/setup_vault_configure_engine_pki/vars/main.yml
  tests/integration/targets/setup_vault_test_plugins/library/vault_ci_enable_engine.py
  tests/unit/fixtures/pki_generate_certificate_response.json
  tests/unit/plugins/modules/conftest.py
  tests/unit/plugins/modules/test_vault_pki_generate_certificate.py
Labels: enhancement

#221 codecov - try different path format
  codecov.yml
Labels: ci

#213 `vault_token_create` - add module and lookup for creating tokens
  .github/actions/ansible-codecov/process.py
  .github/actions/docker-image-versions/versions.py
  codecov.yml
  docs/docsite/rst/filter_guide.rst
  plugins/doc_fragments/auth.py
  plugins/doc_fragments/connection.py
  plugins/doc_fragments/token_create.py
  plugins/lookup/vault_login.py
  plugins/lookup/vault_token_create.py
  plugins/modules/vault_token_create.py
  tests/integration/integration.cfg
  tests/integration/targets/lookup_vault_token_create/aliases
  tests/integration/targets/lookup_vault_token_create/meta/main.yml
  tests/integration/targets/lookup_vault_token_create/tasks/lookup_vault_token_create_setup.yml
  tests/integration/targets/lookup_vault_token_create/tasks/lookup_vault_token_create_test.yml
  tests/integration/targets/lookup_vault_token_create/tasks/main.yml
  tests/integration/targets/module_vault_token_create/aliases
  tests/integration/targets/module_vault_token_create/meta/main.yml
  tests/integration/targets/module_vault_token_create/tasks/main.yml
  tests/integration/targets/module_vault_token_create/tasks/module_vault_token_create_setup.yml
  tests/integration/targets/module_vault_token_create/tasks/module_vault_token_create_test.yml
  tests/integration/targets/setup_vault_configure/tasks/configure.yml
  tests/integration/targets/setup_vault_configure/vars/main.yml
  tests/integration/targets/setup_vault_test_plugins/library/vault_ci_token_create.py
  tests/unit/fixtures/token_create_response.json
  tests/unit/plugins/lookup/test_vault_read.py
  tests/unit/plugins/lookup/test_vault_token_create.py
  tests/unit/plugins/modules/test_vault_token_create.py
Labels: enhancement

#211 docs - lookup guide
  docs/docsite/extra-docs.yml
  docs/docsite/rst/about_hashi_vault_lookup.rst
  docs/docsite/rst/lookup_guide.rst
Labels: documentation
