Repository ansible-collections/community.hashi_vault, pull requests merged in 2022-04, with the labels that each got.

#235 Docs/strict and lenient
  .github/workflows/docs-push.yml
  .github/workflows/docs.yml
  docs/preview/build.sh
  docs/preview/requirements.txt
Labels: documentation

#243 bump deps, add stable-2.13
  .github/workflows/ansible-builder.yml
  .github/workflows/ansible-test.yml
  .github/workflows/github-release.yml
Labels: ci

#245 doc: add example for write using kv v2 engine
  plugins/modules/vault_write.py
Labels: documentation

#246 add content for KV get operations
  changelogs/fragments/246-action_group.yml
  codecov.yml
  docs/docsite/rst/about_hashi_vault_lookup.rst
  docs/docsite/rst/lookup_guide.rst
  meta/runtime.yml
  plugins/doc_fragments/backend_mount.py
  plugins/lookup/vault_kv1_get.py
  plugins/lookup/vault_kv2_get.py
  plugins/modules/vault_kv1_get.py
  plugins/modules/vault_kv2_get.py
  tests/integration/targets/auth_token/tasks/token_test_controller.yml
  tests/integration/targets/auth_token/tasks/token_test_target.yml
  tests/integration/targets/lookup_hashi_vault/tasks/lookup_test.yml
  tests/integration/targets/lookup_vault_kv1_get/aliases
  tests/integration/targets/lookup_vault_kv1_get/meta/main.yml
  tests/integration/targets/lookup_vault_kv1_get/tasks/lookup_vault_kv1_get_setup.yml
  tests/integration/targets/lookup_vault_kv1_get/tasks/lookup_vault_kv1_get_test.yml
  tests/integration/targets/lookup_vault_kv1_get/tasks/main.yml
  tests/integration/targets/lookup_vault_kv2_get/aliases
  tests/integration/targets/lookup_vault_kv2_get/meta/main.yml
  tests/integration/targets/lookup_vault_kv2_get/tasks/lookup_vault_kv2_get_setup.yml
  tests/integration/targets/lookup_vault_kv2_get/tasks/lookup_vault_kv2_get_test.yml
  tests/integration/targets/lookup_vault_kv2_get/tasks/main.yml
  tests/integration/targets/lookup_vault_read/tasks/lookup_vault_read_test.yml
  tests/integration/targets/module_vault_kv1_get/aliases
  tests/integration/targets/module_vault_kv1_get/meta/main.yml
  tests/integration/targets/module_vault_kv1_get/tasks/main.yml
  tests/integration/targets/module_vault_kv1_get/tasks/module_vault_kv1_get_setup.yml
  tests/integration/targets/module_vault_kv1_get/tasks/module_vault_kv1_get_test.yml
  tests/integration/targets/module_vault_kv2_get/aliases
  tests/integration/targets/module_vault_kv2_get/meta/main.yml
  tests/integration/targets/module_vault_kv2_get/tasks/main.yml
  tests/integration/targets/module_vault_kv2_get/tasks/module_vault_kv2_get_setup.yml
  tests/integration/targets/module_vault_kv2_get/tasks/module_vault_kv2_get_test.yml
  tests/integration/targets/module_vault_read/tasks/module_vault_read_test.yml
  tests/integration/targets/setup_vault_configure/tasks/configure.yml
  tests/integration/targets/setup_vault_configure/tasks/main.yml
  tests/integration/targets/setup_vault_configure/vars/main.yml
  tests/integration/targets/setup_vault_test_plugins/library/vault_ci_kv2_destroy_all.py
  tests/integration/targets/setup_vault_test_plugins/vars/main.yml
  tests/unit/fixtures/kv1_get_response.json
  tests/unit/fixtures/kv2_get_response.json
  tests/unit/plugins/lookup/test_vault_kv1_get.py
  tests/unit/plugins/lookup/test_vault_kv2_get.py
  tests/unit/plugins/modules/test_vault_kv1_get.py
  tests/unit/plugins/modules/test_vault_kv2_get.py
Labels: enhancement

#256 add extra-links config
  docs/docsite/links.yml
Labels: documentation
