Repository ansible-collections/community.hashi_vault, pull requests merged in 2022-10, with the labels that each got.

#311 replace set-output in workflows
  .github/actions/docker-image-versions/versions.py
  .github/workflows/ansible-builder.yml
  .github/workflows/ansible-test.yml
  .github/workflows/github-release.yml
Labels: ci

#310 Fix `namespace` value with newer `requests`
  changelogs/fragments/309-stringify-namespace.yml
  plugins/module_utils/_hashi_vault_common.py
  tests/unit/plugins/plugin_utils/authentication/test_auth_token.py
  tests/unit/plugins/plugin_utils/test_hashi_vault_helper.py
Labels: bug

#304 Add vault_kv2_delete module
  meta/runtime.yml
  plugins/modules/vault_kv2_delete.py
  tests/integration/targets/module_vault_kv2_delete/aliases
  tests/integration/targets/module_vault_kv2_delete/meta/main.yml
  tests/integration/targets/module_vault_kv2_delete/tasks/main.yml
  tests/integration/targets/module_vault_kv2_delete/tasks/module_vault_kv2_delete_setup.yml
  tests/integration/targets/module_vault_kv2_delete/tasks/module_vault_kv2_delete_test.yml
  tests/integration/targets/setup_vault_configure/vars/main.yml
  tests/integration/targets/setup_vault_test_plugins/library/vault_ci_kv2_metadata_read.py
  tests/integration/targets/setup_vault_test_plugins/vars/main.yml
  tests/unit/plugins/modules/test_vault_kv2_delete.py
Labels: enhancement, hacktoberfest-accepted
